######################################################################
# Automatically generated by qmake (2.01a) Sun Mar 1 17:26:51 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Answer.h gui.h
SOURCES += Answer.cpp gui.cpp mainGUI.cpp
